applications/biblioteca/urls.py
from django.urls import path

from . import views

app_name = "biblioteca_app"

urlpatterns = [
    path("", views.ListaAuthors.as_view(), name="lista_autores"),
    path("libros-autor/<int:pk>/", views.ListaBooksByAuthor.as_view(), name="lista_libros"),
    path("autor/add/", views.AddAuthor.as_view(), name="autor_add"),
]

applications/home/urls.py
from django.urls import path, re_path
from . import views

app_name = "home_app"

urlpatterns = [
    path('index', views.IndexView.as_view(), name="index"),
    path('libros/', views.ListaLibros.as_view(), name="lista"),
]

libro/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('', include('applications.home.urls')),
    path('', include('applications.biblioteca.urls')),
    path('admin/', admin.site.urls),
]

applications/biblioteca/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField("Nombres", max_length=80)
    nacionality = models.CharField("Nacionalidad", blank=True, max_length=100)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField("Título", max_length=150)
    resume = models.TextField("Resumen", blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

applications/home/models.py
from django.db import models

# Create your models here.

applications/biblioteca/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import Author, Book

class ListaAuthors(ListView):
    template_name = "biblioteca/lista_autores.html"
    queryset = Author.objects.all()
    context_object_name = "autores"

class ListaBooksByAuthor(ListView):
    template_name = "biblioteca/lista_libros.html"
    context_object_name = "libros"

    def get_queryset(self):
        return Book.objects.filter(author_id=self.kwargs["pk"])

class AddAuthor(CreateView):
    template_name = "biblioteca/add_author.html"
    model = Author
    fields = ["name", "nacionality"]
    success_url = "/"

applications/home/views.py
from django.shortcuts import render

from django.views.generic import TemplateView, ListView


class IndexView(TemplateView):
    template_name = "home/index.html"


class ListaLibros(ListView):
    template_name = "home/lista.html"
    queryset = ["El Quijote", "Código limpio", "La sombra del viento", "Django 2.0"]
    context_object_name = "libros"

templates/biblioteca/add_author.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Agregar autor</title>
  </head>
  <body>
    <h1>Agregar autor</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
  </body>
</html>

templates/biblioteca/lista_autores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de autores</title>
</head>
<body>
    <h1>Autores registrados</h1>
    <table border="1">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Nacionalidad</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for autor in autores %}
                <tr>
                    <td>{{ autor.id }}</td>
                    <td>{{ autor.name }}</td>
                    <td>{{ autor.nacionality }}</td>
                    <td>
                        <a href="{% url 'biblioteca_app:lista_libros' autor.id %}">Ver libros</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/biblioteca/lista_libros.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Libros por autor</title>
</head>
<body>
    <h1>Lista de libros por autor</h1>
    <table border="1">
        <thead>
            <th>ID</th>
            <th>Título</th>
            <th>Autor</th>
        </thead>
        <tbody>
            {% for libro in libros %}
                <tr>
                    <td>{{ libro.id }}</td>
                    <td>{{ libro.title }}</td>
                    <td>{{ libro.author.name }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>
</head>
<body>
    <h1>Bienvenido a la biblioteca</h1>
    <p>Esta es la página principal de la biblioteca</p>
    <a href="{% url 'biblioteca_app:lista_autores' %}">Lista de autores</a>
</body>
</html>

templates/home/lista.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista estática</title>
</head>
<body>
    <h1>Lista estática de libros</h1>
    {% for libro in libros%}
        <p>{{ libro }}</p>
    {% endfor %}
</body>
</html>